const cardsOfEachType = {
  onlyBlack: {
    'id': 1,
    'cardSetId': 1,
    'name': 'Ecstatic Awakener',
    'price': 0.06,
    'rarity': 'common',
    'cardNumber': 100,
    'manaCost': 'black',
    'rulesText': '{2}{B}, Sacrifice another creature: Draw a card, then transform Ecstatic Awakener. Activate only once each turn.\n\n//'
  },
  blackWithColorless: {
    'id': 2,
    'cardSetId': 1,
    'name': 'The Meathook Massacre',
    'price': 15.62,
    'rarity': 'mythic',
    'cardNumber': 112,
    'manaCost': 'x black black',
    'rulesText': 'When The Meathook Massacre enters the battlefield, each creature gets -X/-X until end of turn.\nWhenever a creature you control dies, each opponent loses 1 life.\nWhenever a creature an opponent controls dies, you gain 1 life.'
  },
  onlyBlue: {
    'id': 3,
    'cardSetId': 1,
    'name': 'Secrets of the Key',
    'price': 0.06,
    'rarity': 'common',
    'cardNumber': 73,
    'manaCost': 'blue',
    'rulesText': 'Investigate. If this spell was cast from a graveyard, investigate twice instead. (To investigate, create a colorless Clue artifact token with \'{2}, Sacrifice this artifact: Draw a card.\')\nFlashback {3}{U}'
  },
  blueWithColorless:     {
    'id': 4,
    'cardSetId': 1,
    'name': 'Nebelgast Intruder',
    'price': 0.08,
    'rarity': 'uncommon',
    'cardNumber': 64,
    'manaCost': '2 blue',
    'rulesText': 'Flash\nFlying\nWhen Nebelgast Intruder enters the battlefield, up to one target creature an opponent controls gets -2/-0 until end of turn.'
  },
  onlyGreen: {
    'id': 5,
    'cardSetId': 1,
    'name': 'Deathbonnet Sprout',
    'price': 0.14,
    'rarity': 'uncommon',
    'cardNumber': 181,
    'manaCost': 'green',
    'rulesText': 'At the beginning of your upkeep, mill a card. Then if there are three or more creature cards in your graveyard, transform Deathbonnet Sprout. (To mill a card, put the top card of your library into your graveyard.)\n\n//\n\nAt the beginning of your upkeep, you may exile a card from a graveyard. If a creature card was exiled this way, put a +1/+1 counter on Deathbonnet Hulk.'
  },
  greenWithColorless: {
    'id': 6,
    'cardSetId': 1,
    'name': 'Burly Breaker',
    'price': 0.1,
    'rarity': 'uncommon',
    'cardNumber': 174,
    'manaCost': '3 green green',
    'rulesText': 'Ward {1} (Whenever this creature becomes the target of a spell or ability an opponent controls, counter it unless that player pays {1}.)\nDaybound (If a player casts no spells during their own turn, it becomes night next turn.)\n\n//\n\nWard {3} (Whenever this creature becomes the target of a spell or ability an opponent controls, counter it unless that player pays {3}.)\nNightbound (If a player casts at least two spells during their own turn, it becomes day next turn.)'
  },
  onlyRed: {
    'id': 7,
    'cardSetId': 1,
    'name': 'Voldaren Stinger',
    'price': 0.07,
    'rarity': 'common',
    'cardNumber': 167,
    'manaCost': 'red',
    'rulesText': 'Voldaren Stinger has first strike as long as it\'s attacking.\n{2}{R}: Voldaren Stinger gets +2/+0 until end of turn.'
  },
  redWithColorless: {
    'id': 8,
    'cardSetId': 1,
    'name': 'Sunstreak Phoenix',
    'price': 1.73,
    'rarity': 'mythic',
    'cardNumber': 162,
    'manaCost': '2 red red',
    'ruleText': 'Flying\nIf it\'s neither day nor night, it becomes day as Sunstreak Phoenix enters the battlefield.\nWhenever day becomes night or night becomes day, you may pay {1}{R}. If you do, return Sunstreak Phoenix from your graveyard to the battlefield tapped.'
  },
  onlyWhite: {
    'id': 0,
    'cardSetId': 1,
    'name': 'Lunarch Veteran',
    'price': 0.07,
    'rarity': 'common',
    'cardNumber': 27,
    'manaCost': 'white',
    'rulesText': 'Whenever another creature enters the battlefield under your control, you gain 1 life.\nDisturb {1}{W} (You may cast this card from your graveyard transformed for its disturb cost.)\n\n//\n\nFlying\nWhenever another creature you control leaves the battlefield, you gain 1 life.\nIf Luminous Phantom would be put into a graveyard from anywhere, exile it instead.'
  },
  whiteWithColorless: {
    'id': 10,
    'cardSetId': 1,
    'name': 'Enduring Angel',
    'price': 3.07,
    'rarity': 'mythic',
    'cardNumber': 17,
    'manaCost': '2 white white white',
    'rulesText': 'Flying, double strike\nYou have hexproof.\nIf your life total would be reduced to 0 or less, instead transform Enduring Angel and your life total becomes 3. Then if Enduring Angel didn\'t transform this way, you lose the game.\n\n//\n\nFlying\nYou have hexproof.\nAngelic Enforcer\'s power and toughness are each equal to your life total.\nWhenever Angelic Enforcer attacks, double your life total.'
  },
  whiteAndBlue: {
    'id': 11,
    'cardSetId': 1,
    'name': 'Hallowed Respite',
    'price': 0.2,
    'rarity': 'rare',
    'cardNumber': 227,
    'manaCost': 'white blue',
    'rulesText': 'Exile target nonlegendary creature, then return it to the battlefield under its owner\'s control. If it entered under your control, put a +1/+1 counter on it. Otherwise, tap it.\nFlashback {1}{W}{U} (You may cast this card from your graveyard for its flashback cost. Then exile it.)'
  },
  blackAndGreenWithColorless: {
    'id': 12,
    'cardSetId': 1,
    'name': 'Grizzly Ghoul',
    'price': 0.08,
    'rarity': 'uncommon',
    'cardNumber': 226,
    'manaCost': '2 black green',
    'rulesText': 'Trample\nGrizzly Ghoul enters the battlefield with a +1/+1 counter on it for each creature that died this turn.'
  },
  colorlessArtifact: {
    'id': 13,
    'cardSetId': 1,
    'name': 'Mystic Skull',
    'rarity': 'uncommon',
    'cardNumber': 256,
    'manaCost': '2',
    'rulesText': '{1}, {T}: Add one mana of any color.\n{5}, {T}: Transform Mystic Skull.\n\n//\n\nLands you control have \'{T}: Add one mana of any color.\''
  },
  land: {
    'id': 14,
    'cardSetId': 1,
    'name': 'Shipwreck Marsh',
    'price': 3.3,
    'rarity': 'rare',
    'cardNumber': 267,
    'manaCost': '',
    'rulesText': 'Shipwreck Marsh enters the battlefield tapped unless you control two or more other lands.\n{T}: Add {U} or {B}.'
  },
}

const testCards = [
  {
    'price_trend': 0.76,
    'image_path': 'img/hostile_hostel_264.png',
    'name': 'Hostile Hostel',
    'average_price_30_days': 2.07,
    'from_price': 0.98,
    'rarity': 'mythic',
    'average_price_7_days': 1.68,
    'average_price_1_days': 1.62,
    'full_name': 'Hostile Hostel // Creeping Inn',
    'card_number': 264,
    'mana_cost': '',
    'rules_text': '{T}: Add {C}.\n{1}, {T}, Sacrifice a creature: Put a soul counter on Hostile Hostel. Then if there are three or more soul counters on it, remove those counters, transform it, then untap it. Activate only as a sorcery.\n\n//\n\nWhenever Creeping Inn attacks, you may exile a creature card from your graveyard. If you do, each opponent loses X life and you gain X life, where X is the number of creature cards exiled with Creeping Inn.\n{4}: Creeping Inn phases out.'
  },
  {
    'price_trend': 0.1,
    'image_path': 'img/mystic_skull_256.png',
    'name': 'Mystic Skull',
    'average_price_30_days': 0.09,
    'from_price': 0.01,
    'rarity': 'uncommon',
    'average_price_7_days': 0.08,
    'average_price_1_days': 0.06,
    'full_name': 'Mystic Skull // Mystic Monstrosity',
    'card_number': 256,
    'mana_cost': '2',
    'rules_text': '{1}, {T}: Add one mana of any color.\n{5}, {T}: Transform Mystic Skull.\n\n//\n\nLands you control have \'{T}: Add one mana of any color.\''
  },
  {
    'price_trend': 2.69,
    'image_path': 'img/tovolar_dire_overlord_246.png',
    'name': 'Tovolar, Dire Overlord',
    'average_price_30_days': 2.75,
    'from_price': 1.7,
    'rarity': 'rare',
    'average_price_7_days': 2.85,
    'average_price_1_days': 2.75,
    'full_name': 'Tovolar, Dire Overlord // Tovolar, the Midnight Scourge',
    'card_number': 246,
    'mana_cost': '1 red green',
    'rules_text': 'Whenever a Wolf or Werewolf you control deals combat damage to a player, draw a card.\nAt the beginning of your upkeep, if you control three or more Wolves and/or Werewolves, it becomes night. Then transform any number of Human Werewolves you control.\nDaybound\n\n//\n\nWhenever a Wolf or Werewolf you control deals combat damage to a player, draw a card.\n{X}{R}{G}: Target Wolf or Werewolf you control gets +X/+0 and gains trample until end of turn.\nNightbound'
  },
  {
    'price_trend': 0.12,
    'image_path': 'img/ludevic_necrogenius_233.png',
    'name': 'Ludevic, Necrogenius',
    'average_price_30_days': 0.4,
    'from_price': 0.09,
    'rarity': 'rare',
    'average_price_7_days': 0.28,
    'average_price_1_days': 0.24,
    'full_name': 'Ludevic, Necrogenius // Olag, Ludevic\'s Hubris',
    'card_number': 233,
    'mana_cost': 'blue black',
    'rules_text': 'Whenever Ludevic, Necrogenius enters the battlefield or attacks, mill a card.\n{X}{U}{U}{B}{B}, Exile X creature cards from your graveyard: Transform Ludevic. X can\'t be 0. Activate only as a sorcery.\n\n//\n\nAs this creature transforms into Olag, Ludevic\'s Hubris, it becomes a copy of a creature card exiled with it, except its name is Olag, Ludevic\'s Hubris, it\'s 4/4, and it\'s a legendary blue and black Zombie in addition to its other colors and types. Put a number of +1/+1 counters on Olag equal to the number of creature cards exiled with it.'
  },
  {
    'price_trend': 0.17,
    'image_path': 'img/kessig_naturalist_231.png',
    'name': 'Kessig Naturalist',
    'average_price_30_days': 0.14,
    'from_price': 0.02,
    'rarity': 'uncommon',
    'average_price_7_days': 0.15,
    'average_price_1_days': 0.15,
    'full_name': 'Kessig Naturalist // Lord of the Ulvenwald',
    'card_number': 231,
    'mana_cost': 'red green',
    'rules_text': 'Whenever Kessig Naturalist attacks, add {R} or {G}. Until end of turn, you don\'t lose this mana as steps and phases end.\nDaybound (If a player casts no spells during their own turn, it becomes night next turn.)\n\n//\n\nOther Wolves and Werewolves you control get +1/+1.\nWhenever Lord of the Ulvenwald attacks, add {R} or {G}. Until end of turn, you don\'t lose this mana as steps and phases end.\nNightbound (If a player casts at least two spells during their own turn, it becomes day next turn.)'
  },
  {
    'price_trend': 0.09,
    'image_path': 'img/devoted_grafkeeper_218.png',
    'name': 'Devoted Grafkeeper',
    'average_price_30_days': 0.09,
    'from_price': 0.02,
    'rarity': 'uncommon',
    'average_price_7_days': 0.1,
    'average_price_1_days': 0.08,
    'full_name': 'Devoted Grafkeeper // Departed Soulkeeper',
    'card_number': 218,
    'mana_cost': 'white blue',
    'rules_text': 'When Devoted Grafkeeper enters the battlefield, mill two cards.\nWhenever you cast a spell from your graveyard, tap target creature you don\'t control.\nDisturb {1}{W}{U} (You may cast this card from your graveyard transformed for its disturb cost.)\n\n//\n\nFlying\nDeparted Soulkeeper can block only creatures with flying.\nIf Departed Soulkeeper would be put into a graveyard from anywhere, exile it instead.'
  },
  {
    'price_trend': 0.13,
    'image_path': 'img/dennick_pious_apprentice_217.png',
    'name': 'Dennick, Pious Apprentice',
    'average_price_30_days': 0.35,
    'from_price': 0.08,
    'rarity': 'rare',
    'average_price_7_days': 0.27,
    'average_price_1_days': 0.22,
    'full_name': 'Dennick, Pious Apprentice // Dennick, Pious Apparition',
    'card_number': 217,
    'mana_cost': 'white blue',
    'rules_text': 'Lifelink\nCards in graveyards can\'t be the targets of spells or abilities.\nDisturb {2}{W}{U} (You may cast this card from your graveyard transformed for its disturb cost.)\n\n//\n\nFlying\nWhenever one or more creature cards are put into graveyards from anywhere, investigate. This ability triggers only once each turn. (Create a colorless Clue artifact token with \'{2}, Sacrifice this artifact: Draw a card.\')\nIf Dennick, Pious Apparition would be put into a graveyard from anywhere, exile it instead.'
  },
  {
    'price_trend': 7.48,
    'image_path': 'img/arlinn_the_packs_hope_211.png',
    'name': 'Arlinn, the Pack\'s Hope',
    'average_price_30_days': 8.48,
    'from_price': 6.99,
    'rarity': 'mythic',
    'average_price_7_days': 8.71,
    'average_price_1_days': 9.32,
    'full_name': 'Arlinn, the Pack\'s Hope // Arlinn, the Moon\'s Fury',
    'card_number': 211,
    'mana_cost': '2 red green',
    'rules_text': 'Daybound (If a player casts no spells during their own turn, it becomes night next turn.)\n+1: Until your next turn, you may cast creature spells as though they had flash, and each creature you control enters the battlefield with an additional +1/+1 counter on it.\n\u22123: Create two 2/2 green Wolf creature tokens.\n\n//\n\nNightbound (If a player casts at least two spells during their own turn, it becomes day next turn.)\n+2: Add {R}{G}.\n0: Until end of turn, Arlinn, the Moon\'s Fury becomes a 5/5 Werewolf creature with trample, indestructible, and haste.'
  },
  {
    'price_trend': 0.87,
    'image_path': 'img/tovolars_huntmaster_204.png',
    'name': 'Tovolar\'s Huntmaster',
    'average_price_30_days': 0.97,
    'from_price': 0.25,
    'rarity': 'rare',
    'average_price_7_days': 0.95,
    'average_price_1_days': 0.99,
    'full_name': 'Tovolar\'s Huntmaster // Tovolar\'s Packleader',
    'card_number': 204,
    'mana_cost': '4 green green',
    'rules_text': 'When Tovolar\'s Huntmaster enters the battlefield, create two 2/2 green Wolf creature tokens.\nDaybound (If a player casts no spells during their own turn, it becomes night next turn.)\n\n//\n\nWhenever Tovolar\'s Packleader enters the battlefield or attacks, create two 2/2 green Wolf creature tokens.\n{2}{G}{G}: Another target Wolf or Werewolf you control fights target creature you don\'t control.\nNightbound (If a player casts at least two spells during their own turn, it becomes day next turn.)'
  },
  {
    'price_trend': 0.07,
    'image_path': 'img/tireless_hauler_203.png',
    'name': 'Tireless Hauler',
    'average_price_30_days': 0.05,
    'from_price': 0.01,
    'rarity': 'common',
    'average_price_7_days': 0.05,
    'average_price_1_days': 0.2,
    'full_name': 'Tireless Hauler // Dire-Strain Brawler',
    'card_number': 203,
    'mana_cost': '4 green',
    'rules_text': 'Vigilance\nDaybound (If a player casts no spells during their own turn, it becomes night next turn.)\n\n//\n\nVigilance\nNightbound (If a player casts at least two spells during their own turn, it becomes day next turn.)'
  },
  {
    'price_trend': 0.2,
    'image_path': 'img/outland_liberator_190.png',
    'name': 'Outland Liberator',
    'average_price_30_days': 0.16,
    'from_price': 0.02,
    'rarity': 'uncommon',
    'average_price_7_days': 0.18,
    'average_price_1_days': 0.19,
    'full_name': 'Outland Liberator // Frenzied Trapbreaker',
    'card_number': 190,
    'mana_cost': '1 green',
    'rules_text': '{1}, Sacrifice Outland Liberator: Destroy target artifact or enchantment.\nDaybound (If a player casts no spells during their own turn, it becomes night next turn.)\n\n//\n\n{1}, Sacrifice Frenzied Trapbreaker: Destroy target artifact or enchantment.\nWhenever Frenzied Trapbreaker attacks, destroy target artifact or enchantment defending player controls.\nNightbound (If a player casts at least two spells during their own turn, it becomes day next turn.)'
  },
  {
    'price_trend': 0.13,
    'image_path': 'img/hound_tamer_187.png',
    'name': 'Hound Tamer',
    'average_price_30_days': 0.12,
    'from_price': 0.02,
    'rarity': 'uncommon',
    'average_price_7_days': 0.12,
    'average_price_1_days': 0.12,
    'full_name': 'Hound Tamer // Untamed Pup',
    'card_number': 187,
    'mana_cost': '2 green',
    'rules_text': 'Trample\n{3}{G}: Put a +1/+1 counter on target creature.\nDaybound (If a player casts no spells during their own turn, it becomes night next turn.)\n\n//\n\nTrample\nOther Wolves and Werewolves you control have trample.\n{3}{G}: Put a +1/+1 counter on target creature.\nNightbound (If a player casts at least two spells during their own turn, it becomes day next turn.)'
  },
]

export { cardsOfEachType, testCards }